### ISSUE TITLE
[Bug] Report

### ISSUE THREAD

**Issue by webcaetano** [SamVerschueren/dev-time-cli#4]
```
C:\Users\Andre\MEGA\game\wizz>dev-time SamVerschueren
C:\Users\Andre\AppData\Roaming\npm\node_modules\dev-time-cli\cli.js:3
const updateNotifier = require('update-notifier');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

OS : Win 8.0
Node : 0.12.0
Npm: 2.5.1

**Comment by SamVerschueren** [comment]
Upgrade node to >=4.x

**Comment by webcaetano** [comment]
It work, thanks.
I should have nvm and tested it before create this issue.

**Comment by SamVerschueren** [comment]
No problem, glad you like it :)
